user properties in edit form
DevGroup-ru/yii2-users-module pull request #3
Opened 2016-11-03 10:39 UTC by Nimoto

2016-11-03 10:54 UTC, bethrezen approved these changes
Approved with minor issue

2016-11-03 10:54 UTC, bethrezen commented on src/actions/BackendEditUser.php
> +                    $attributes = array_merge($attributes, $post["User"]);
Please use single quotes if you don't need variables inside string

2016-11-07 10:48 UTC, ivansal requested changes

2016-11-07 10:48 UTC, ivansal commented on src/actions/BackendEditUser.php
> +                    if (isset($post["User"]) && !empty($post["User"])) {
Change pls to single

2016-11-07 10:48 UTC, ivansal commented on src/actions/BackendEditUser.php
> +                        $users = [User::find()->where(["id" => $user->id])->one()];
same

2016-11-07 10:48 UTC, ivansal commented on src/actions/BackendEditUser.php
> +                        $users[0]->setAttributes($post["User"]);
same

2016-11-08 06:40 UTC, merged